// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/cosmos/tx/v1beta1/tx.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tx is the standard type used for broadcasting transactions.
// This is a minimal subset of the full cosmos.tx.v1beta1.Tx message,
// containing only the fields needed by go-square.
type Tx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *TxBody                `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tx) Reset() {
	*x = Tx{}
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_tx_v1beta1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Tx) GetBody() *TxBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// TxBody is the body of a transaction that all signers sign over.
// This is a minimal subset containing only the messages field.
type TxBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*anypb.Any           `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBody) Reset() {
	*x = TxBody{}
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBody) ProtoMessage() {}

func (x *TxBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBody.ProtoReflect.Descriptor instead.
func (*TxBody) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_tx_v1beta1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxBody) GetMessages() []*anypb.Any {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_cosmos_tx_v1beta1_tx_proto protoreflect.FileDescriptor

const file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc = "" +
	"\n" +
	" proto/cosmos/tx/v1beta1/tx.proto\x12\x17proto.cosmos.tx.v1beta1\x1a\x19google/protobuf/any.proto\"9\n" +
	"\x02Tx\x123\n" +
	"\x04body\x18\x01 \x01(\v2\x1f.proto.cosmos.tx.v1beta1.TxBodyR\x04body\":\n" +
	"\x06TxBody\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\bmessagesB=Z;github.com/celestiaorg/go-square/v4/proto/cosmos/tx/v1beta1b\x06proto3"

var (
	file_proto_cosmos_tx_v1beta1_tx_proto_rawDescOnce sync.Once
	file_proto_cosmos_tx_v1beta1_tx_proto_rawDescData []byte
)

func file_proto_cosmos_tx_v1beta1_tx_proto_rawDescGZIP() []byte {
	file_proto_cosmos_tx_v1beta1_tx_proto_rawDescOnce.Do(func() {
		file_proto_cosmos_tx_v1beta1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc), len(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc)))
	})
	return file_proto_cosmos_tx_v1beta1_tx_proto_rawDescData
}

var file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cosmos_tx_v1beta1_tx_proto_goTypes = []any{
	(*Tx)(nil),        // 0: proto.cosmos.tx.v1beta1.Tx
	(*TxBody)(nil),    // 1: proto.cosmos.tx.v1beta1.TxBody
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_proto_cosmos_tx_v1beta1_tx_proto_depIdxs = []int32{
	1, // 0: proto.cosmos.tx.v1beta1.Tx.body:type_name -> proto.cosmos.tx.v1beta1.TxBody
	2, // 1: proto.cosmos.tx.v1beta1.TxBody.messages:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cosmos_tx_v1beta1_tx_proto_init() }
func file_proto_cosmos_tx_v1beta1_tx_proto_init() {
	if File_proto_cosmos_tx_v1beta1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc), len(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cosmos_tx_v1beta1_tx_proto_goTypes,
		DependencyIndexes: file_proto_cosmos_tx_v1beta1_tx_proto_depIdxs,
		MessageInfos:      file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes,
	}.Build()
	File_proto_cosmos_tx_v1beta1_tx_proto = out.File
	file_proto_cosmos_tx_v1beta1_tx_proto_goTypes = nil
	file_proto_cosmos_tx_v1beta1_tx_proto_depIdxs = nil
}
