// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/cosmos/tx/v1beta1/tx.proto

package v1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TxRaw is the transaction as it travels on the wire, and mirrors the message
// the Cosmos SDK decodes raw transaction bytes into. This is a minimal subset of
// the full cosmos.tx.v1beta1.TxRaw, containing only the fields needed by
// go-square, but the wire-level shape is deliberately identical: go-square and
// the SDK must never disagree about what a given set of transaction bytes says.
//
// Modelling body_bytes as a scalar `bytes` field rather than an embedded TxBody
// message is the load-bearing part. Repeated occurrences of a scalar field
// resolve to the last one, whereas repeated occurrences of a message field are
// merged and their inner repeated fields concatenated. Only the former matches
// the SDK.
type TxRaw struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// body_bytes is a protobuf serialization of a TxBody that matches the
	// representation in SignDoc.
	BodyBytes []byte `protobuf:"bytes,1,opt,name=body_bytes,json=bodyBytes,proto3" json:"body_bytes,omitempty"`
	// auth_info_bytes is a protobuf serialization of an AuthInfo that matches the
	// representation in SignDoc. go-square does not decode it; it is declared so
	// that this message stays a faithful view of the bytes the SDK sees.
	AuthInfoBytes []byte `protobuf:"bytes,2,opt,name=auth_info_bytes,json=authInfoBytes,proto3" json:"auth_info_bytes,omitempty"`
	// signatures is a list of signatures that matches the length and order of
	// AuthInfo's signer_infos to allow connecting signature meta information like
	// public key and signing mode by position.
	Signatures    [][]byte `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxRaw) Reset() {
	*x = TxRaw{}
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxRaw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRaw) ProtoMessage() {}

func (x *TxRaw) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRaw.ProtoReflect.Descriptor instead.
func (*TxRaw) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_tx_v1beta1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxRaw) GetBodyBytes() []byte {
	if x != nil {
		return x.BodyBytes
	}
	return nil
}

func (x *TxRaw) GetAuthInfoBytes() []byte {
	if x != nil {
		return x.AuthInfoBytes
	}
	return nil
}

func (x *TxRaw) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// TxBody is the body of a transaction that all signers sign over.
// This is a minimal subset containing only the messages field.
type TxBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*anypb.Any           `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBody) Reset() {
	*x = TxBody{}
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBody) ProtoMessage() {}

func (x *TxBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBody.ProtoReflect.Descriptor instead.
func (*TxBody) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_tx_v1beta1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxBody) GetMessages() []*anypb.Any {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Tx models the body as an embedded message, which does NOT match how the
// Cosmos SDK reads the same wire field. Decoding transaction bytes through this
// message can reach a different answer than the SDK does about which messages a
// transaction contains. Decode through TxRaw instead.
//
// Retained only so that removing it is not a breaking change for the published
// module; nothing in go-square uses it.
//
// Deprecated: Marked as deprecated in proto/cosmos/tx/v1beta1/tx.proto.
type Tx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *TxBody                `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tx) Reset() {
	*x = Tx{}
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_tx_v1beta1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *Tx) GetBody() *TxBody {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_proto_cosmos_tx_v1beta1_tx_proto protoreflect.FileDescriptor

const file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc = "" +
	"\n" +
	" proto/cosmos/tx/v1beta1/tx.proto\x12\x17proto.cosmos.tx.v1beta1\x1a\x19google/protobuf/any.proto\"n\n" +
	"\x05TxRaw\x12\x1d\n" +
	"\n" +
	"body_bytes\x18\x01 \x01(\fR\tbodyBytes\x12&\n" +
	"\x0fauth_info_bytes\x18\x02 \x01(\fR\rauthInfoBytes\x12\x1e\n" +
	"\n" +
	"signatures\x18\x03 \x03(\fR\n" +
	"signatures\":\n" +
	"\x06TxBody\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\bmessages\"=\n" +
	"\x02Tx\x123\n" +
	"\x04body\x18\x01 \x01(\v2\x1f.proto.cosmos.tx.v1beta1.TxBodyR\x04body:\x02\x18\x01B=Z;github.com/celestiaorg/go-square/v4/proto/cosmos/tx/v1beta1b\x06proto3"

var (
	file_proto_cosmos_tx_v1beta1_tx_proto_rawDescOnce sync.Once
	file_proto_cosmos_tx_v1beta1_tx_proto_rawDescData []byte
)

func file_proto_cosmos_tx_v1beta1_tx_proto_rawDescGZIP() []byte {
	file_proto_cosmos_tx_v1beta1_tx_proto_rawDescOnce.Do(func() {
		file_proto_cosmos_tx_v1beta1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc), len(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc)))
	})
	return file_proto_cosmos_tx_v1beta1_tx_proto_rawDescData
}

var file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_cosmos_tx_v1beta1_tx_proto_goTypes = []any{
	(*TxRaw)(nil),     // 0: proto.cosmos.tx.v1beta1.TxRaw
	(*TxBody)(nil),    // 1: proto.cosmos.tx.v1beta1.TxBody
	(*Tx)(nil),        // 2: proto.cosmos.tx.v1beta1.Tx
	(*anypb.Any)(nil), // 3: google.protobuf.Any
}
var file_proto_cosmos_tx_v1beta1_tx_proto_depIdxs = []int32{
	3, // 0: proto.cosmos.tx.v1beta1.TxBody.messages:type_name -> google.protobuf.Any
	1, // 1: proto.cosmos.tx.v1beta1.Tx.body:type_name -> proto.cosmos.tx.v1beta1.TxBody
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cosmos_tx_v1beta1_tx_proto_init() }
func file_proto_cosmos_tx_v1beta1_tx_proto_init() {
	if File_proto_cosmos_tx_v1beta1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc), len(file_proto_cosmos_tx_v1beta1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cosmos_tx_v1beta1_tx_proto_goTypes,
		DependencyIndexes: file_proto_cosmos_tx_v1beta1_tx_proto_depIdxs,
		MessageInfos:      file_proto_cosmos_tx_v1beta1_tx_proto_msgTypes,
	}.Build()
	File_proto_cosmos_tx_v1beta1_tx_proto = out.File
	file_proto_cosmos_tx_v1beta1_tx_proto_goTypes = nil
	file_proto_cosmos_tx_v1beta1_tx_proto_depIdxs = nil
}
