package tx

import "github.com/celestiaorg/go-square/v4/share"

// FibreTx wraps a MsgPayForFibre SDK transaction with the system-level blob
// generated by the state machine. This type is used internally during square
// construction and is never stored by CometBFT, so standard transaction
// querying works.
type FibreTx struct {
	Tx         []byte
	SystemBlob *share.Blob
}
