package tx

import (
	"errors"

	v4 "github.com/celestiaorg/go-square/v4/proto/blob/v4"
	"github.com/celestiaorg/go-square/v4/share"
	"google.golang.org/protobuf/proto"
)

const (
	// ProtoFibreTxTypeID is included in each encoded FibreTx to help prevent
	// decoding binaries that are not actually FibreTxs.
	ProtoFibreTxTypeID = "FIBR"
)

// FibreTx wraps a MsgPayForFibre SDK transaction with the system-level blob
// generated by the state machine. This wrapper is only used internally during
// square construction (PrepareProposal/ProcessProposal) and is never stored by
// CometBFT, so standard transaction querying works.
type FibreTx struct {
	Tx         []byte
	SystemBlob *share.Blob
}

// UnmarshalFibreTx attempts to unmarshal a transaction into a FibreTx. It
// returns a boolean indicating if the bytes are of type FibreTx and an error
// if there is a problem with decoding.
func UnmarshalFibreTx(tx []byte) (*FibreTx, bool, error) {
	fTx := v4.FibreTx{}
	err := proto.Unmarshal(tx, &fTx)
	if err != nil {
		return nil, false, err
	}
	if fTx.TypeId != ProtoFibreTxTypeID {
		return nil, false, errors.New("invalid type id")
	}
	if fTx.SystemBlob == nil {
		return nil, true, errors.New("no system blob provided")
	}
	systemBlob, err := share.NewBlobFromProto(fTx.SystemBlob)
	if err != nil {
		return nil, true, err
	}
	return &FibreTx{
		Tx:         fTx.Tx,
		SystemBlob: systemBlob,
	}, true, nil
}

// MarshalFibreTx creates a FibreTx using a MsgPayForFibre SDK transaction
// and a system-level blob.
func MarshalFibreTx(tx []byte, systemBlob *share.Blob) ([]byte, error) {
	if systemBlob == nil || systemBlob.IsEmpty() {
		return nil, errors.New("system blob must be provided")
	}
	fTx := &v4.FibreTx{
		Tx: tx,
		SystemBlob: &v4.BlobProto{
			NamespaceId:      systemBlob.Namespace().ID(),
			NamespaceVersion: uint32(systemBlob.Namespace().Version()),
			ShareVersion:     uint32(systemBlob.ShareVersion()),
			Signer:           systemBlob.Signer(),
			Data:             systemBlob.Data(),
		},
		TypeId: ProtoFibreTxTypeID,
	}
	return proto.Marshal(fTx)
}
