// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/celestia/fibre/v1/tx.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgPayForFibre contains the original payment promise with validator
// signatures. This is a minimal subset of the full MsgPayForFibre message from
// celestia-app, containing only the fields needed by go-square.
type MsgPayForFibre struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Signer         string                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	PaymentPromise *PaymentPromise        `protobuf:"bytes,2,opt,name=payment_promise,json=paymentPromise,proto3" json:"payment_promise,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MsgPayForFibre) Reset() {
	*x = MsgPayForFibre{}
	mi := &file_proto_celestia_fibre_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPayForFibre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPayForFibre) ProtoMessage() {}

func (x *MsgPayForFibre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_celestia_fibre_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPayForFibre.ProtoReflect.Descriptor instead.
func (*MsgPayForFibre) Descriptor() ([]byte, []int) {
	return file_proto_celestia_fibre_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgPayForFibre) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *MsgPayForFibre) GetPaymentPromise() *PaymentPromise {
	if x != nil {
		return x.PaymentPromise
	}
	return nil
}

// PaymentPromise is a promise to pay for a fibre blob. This is a minimal subset
// of the full PaymentPromise message from celestia-app, containing only the
// fields needed by go-square.
type PaymentPromise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     []byte                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	BlobVersion   uint32                 `protobuf:"varint,5,opt,name=blob_version,json=blobVersion,proto3" json:"blob_version,omitempty"`
	Commitment    []byte                 `protobuf:"bytes,6,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentPromise) Reset() {
	*x = PaymentPromise{}
	mi := &file_proto_celestia_fibre_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentPromise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentPromise) ProtoMessage() {}

func (x *PaymentPromise) ProtoReflect() protoreflect.Message {
	mi := &file_proto_celestia_fibre_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentPromise.ProtoReflect.Descriptor instead.
func (*PaymentPromise) Descriptor() ([]byte, []int) {
	return file_proto_celestia_fibre_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentPromise) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *PaymentPromise) GetBlobVersion() uint32 {
	if x != nil {
		return x.BlobVersion
	}
	return 0
}

func (x *PaymentPromise) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

var File_proto_celestia_fibre_v1_tx_proto protoreflect.FileDescriptor

const file_proto_celestia_fibre_v1_tx_proto_rawDesc = "" +
	"\n" +
	" proto/celestia/fibre/v1/tx.proto\x12\x11celestia.fibre.v1\"t\n" +
	"\x0eMsgPayForFibre\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\tR\x06signer\x12J\n" +
	"\x0fpayment_promise\x18\x02 \x01(\v2!.celestia.fibre.v1.PaymentPromiseR\x0epaymentPromise\"q\n" +
	"\x0ePaymentPromise\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\fR\tnamespace\x12!\n" +
	"\fblob_version\x18\x05 \x01(\rR\vblobVersion\x12\x1e\n" +
	"\n" +
	"commitment\x18\x06 \x01(\fR\n" +
	"commitmentB=Z;github.com/celestiaorg/go-square/v4/proto/celestia/fibre/v1b\x06proto3"

var (
	file_proto_celestia_fibre_v1_tx_proto_rawDescOnce sync.Once
	file_proto_celestia_fibre_v1_tx_proto_rawDescData []byte
)

func file_proto_celestia_fibre_v1_tx_proto_rawDescGZIP() []byte {
	file_proto_celestia_fibre_v1_tx_proto_rawDescOnce.Do(func() {
		file_proto_celestia_fibre_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_celestia_fibre_v1_tx_proto_rawDesc), len(file_proto_celestia_fibre_v1_tx_proto_rawDesc)))
	})
	return file_proto_celestia_fibre_v1_tx_proto_rawDescData
}

var file_proto_celestia_fibre_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_celestia_fibre_v1_tx_proto_goTypes = []any{
	(*MsgPayForFibre)(nil), // 0: celestia.fibre.v1.MsgPayForFibre
	(*PaymentPromise)(nil), // 1: celestia.fibre.v1.PaymentPromise
}
var file_proto_celestia_fibre_v1_tx_proto_depIdxs = []int32{
	1, // 0: celestia.fibre.v1.MsgPayForFibre.payment_promise:type_name -> celestia.fibre.v1.PaymentPromise
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_celestia_fibre_v1_tx_proto_init() }
func file_proto_celestia_fibre_v1_tx_proto_init() {
	if File_proto_celestia_fibre_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_celestia_fibre_v1_tx_proto_rawDesc), len(file_proto_celestia_fibre_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_celestia_fibre_v1_tx_proto_goTypes,
		DependencyIndexes: file_proto_celestia_fibre_v1_tx_proto_depIdxs,
		MessageInfos:      file_proto_celestia_fibre_v1_tx_proto_msgTypes,
	}.Build()
	File_proto_celestia_fibre_v1_tx_proto = out.File
	file_proto_celestia_fibre_v1_tx_proto_goTypes = nil
	file_proto_celestia_fibre_v1_tx_proto_depIdxs = nil
}
