name: goreleaser
on:
  workflow_call:
    secrets:
      GORELEASER_ACCESS_TOKEN:
        required: true

env:
  GO_VERSION: '1.21.1'

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: check

  goreleaser:
    needs: goreleaser-check
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Create .release-env file
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' >> .release-env
      - name: Create prebuilt binaries and attach them to the GitHub release
        run: make prebuilt-binary
